css-canvas-medical | Rocky Truong
rocky-truong/c0521-code-solutions pull request #32
Opened 2021-05-13 11:49 UTC by rocky-truong

![image](https://user-images.githubusercontent.com/58172952/118121622-9921bc00-b3a6-11eb-8d76-2c28d77bc36d.png)

2021-05-13 11:50 UTC, rocky-truong commented
![image](https://user-images.githubusercontent.com/58172952/118121677-accd2280-b3a6-11eb-8191-8848ad9adeca.png)

2021-05-13 21:54 UTC, rocky-truong commented
![image](https://user-images.githubusercontent.com/58172952/118192503-16771c00-b3fb-11eb-9871-096b5ef22198.png)

2021-05-14 16:51 UTC, codingcodymiller requested changes
Great work on this, dude!! A couple notes for you:

2021-05-14 16:51 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  margin-bottom: 530px;
Woah, that's a big one!! Why is this necessary? We may be able to solve this a different way

2021-05-14 16:51 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
Some big movements here, too. You might be able to reduce the overall changes by putting these elements in their own container, and just absolute positioning that one container

2021-05-22 00:42 UTC, rocky-truong commented
![image](https://user-images.githubusercontent.com/58172952/119209524-f7603600-ba5b-11eb-88c3-fe03ee9b818b.png)

2021-05-27 17:52 UTC, codingcodymiller approved these changes

2021-05-31 04:19 UTC, merged