string-manipulation-1 | Rocky Truong
rocky-truong/c0521-code-solutions pull request #34
Opened 2021-05-13 23:47 UTC by rocky-truong

![image](https://user-images.githubusercontent.com/58172952/118200826-e46db600-b40a-11eb-862a-ceef3828cf3b.png)

2021-05-13 23:56 UTC, codingcodymiller requested changes
Great work on this, dude!! One note for you:

2021-05-13 23:56 UTC, codingcodymiller commented on string-manipulation-1/src/reverse-word.js
> +  }
If you do this loop in reverse instead, I bet you can simplify this

2021-05-14 00:42 UTC, rocky-truong commented
![image](https://user-images.githubusercontent.com/58172952/118204203-89d85800-b412-11eb-814d-326e71e2bf32.png)

2021-05-14 01:16 UTC, codingcodymiller approved these changes

2021-05-14 09:45 UTC, merged