javascript-modal | Rocky Truong
rocky-truong/c0521-code-solutions pull request #45
Opened 2021-05-18 23:31 UTC by rocky-truong

![js modal demo](https://user-images.githubusercontent.com/58172952/118736070-85d37e00-b7f6-11eb-8a63-e1c237e48ce6.gif)

2021-05-19 16:20 UTC, codingcodymiller requested changes
Great work!! A couple notes for you:

2021-05-19 16:20 UTC, codingcodymiller commented on javascript-modal/main.js
> +function modalHandler(event) {
How about `openModal`?

2021-05-19 16:20 UTC, codingcodymiller commented on javascript-modal/main.js
> +function noHandler(event) {
How about `closeModal`?

2021-05-21 07:27 UTC, rocky-truong commented
Uploading javascriptModal gif.mp4…

2021-05-21 17:18 UTC, codingcodymiller approved these changes

2021-05-21 22:14 UTC, merged